name: moodcanvas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.1.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.0 # Check for the latest version
  provider: ^6.1.1
  carousel_slider: ^4.2.1
  google_fonts:
  url_launcher:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/Animals/Bunny/
    - assets/Animals/Chicken/
    - assets/Animals/Lizard/
    - assets/Animals/Panda/
    - assets/moods/
    - assets/logo_colors/
    - assets/ResourcePics/
